### PR TITLE
feat: report suisei cv ci

### PR DESCRIPTION
**Pull request by sorewachigauyo**
Add new suisei cvcis to night battle reporter

New types are `CV_NF_B_S`, `CV_NB_S` and `CV_NF_S`

### CODE REVIEW

**Comment by KagamiChan** [comment]
thanks for your PR. just want to confirm if the judgement order is the same in game, for a CV's equipments satisfying multiple cases. I'm not familiar with these new CI

**Comment by sorewachigauyo** [comment]
Not really sure about judgement order, since new CI will reroll for next capable if fail
So far from DB data, order seems to be 3 equip CI > 2 equip CI

Though, its rare case to happen to satisfy multiple cases of 3 equip CI since you need 4 night capable planes and only Saratoga mod2 can fulfill it

**Comment by KagamiChan** [comment]
Yeah, agreed that it is hard to tell. If the noise is ignorable in case we used a wrong order, we could keep this. Otherwise we could use an array for holding all the possible CI, just as what we have in AACI reports, or use an array for equipment ID instead. I'd like to hear your opinion since you'll likely consume the data

**Comment by KagamiChan** [comment]
Oh, we already have equipment ID reported, so it is possible to recover the details

**Comment by sorewachigauyo** [comment]
Yeah, the order doesn't affect me since I can check which CI proc'd from display/filter from equipment if needed.
Its easy to work with in the current state.

**Pull request merged**
